# - name: Copy backend files
#   become: true
#   copy:
#     src: /home/backend.tar.gz
#     dest: /home/ubuntu/backend.tar.gz

# - name: Start PM2
#   shell: |
#     cd /home/ubuntu/
#     tar xzvf backend.tar.gz
#     mv home/circleci/project/backend .
#     cd backend
#     sudo npm install -g npm@latest
#     sudo npm install -g webpack-dev-server
#     sudo npm install
#     sudo npm run build
#     sudo pm2 start npm --name backend -- start


# ---
# - name: "install dependencies."
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

# - name: Copy backend dist files web server
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

# - name: Install Node
#   shell: |
#     cd /home/ubuntu/backend
#     sudo npm install -g npm@latest
#     sudo npm install -g webpack-dev-server
#     npm install

# - name: Build Node
#   shell: |
#     cd /home/ubuntu/backend
#     npm run build
    
# - name: Start PM2
#   shell: |
#     cd /home/ubuntu/backend
#     pm2 start npm --name backend -- start


- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "copy backend file"
  become: true
  copy:
    src: /root/project/backend
    dest: /root
    force: no

# - name: Install Node
#   shell: |
#     cd /home/ubuntu/backend
#     sudo npm install -g npm@latest
#     sudo npm install -g webpack-dev-server
#     npm install 
    
- name: "install npm packages"
  become: true
  command: npm install
  args:
    chdir: /root/backend

- name: "compile npm packages"
  become: true
  command: npm run build
  args:
    chdir: /root/backend


- name: "start server"
  become: true
  command: pm2 start npm -- run start
  args:
    chdir: /root/backend/dist